-- MySQL Script generated by MySQL Workbench
-- Tue 26 Nov 2019 02:01:20 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `imobiliaria` ;

-- -----------------------------------------------------
-- Table `imobiliaria`.`Proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`Proprietario` (
  `id_proprietario` INT NOT NULL,
  `cpf_proprietario` VARCHAR(11) NOT NULL,
  `nome_proprietario` VARCHAR(100) NOT NULL,
  `email_proprietario` VARCHAR(45) NOT NULL,
  `nascimento_proprietario` DATE NOT NULL,
  PRIMARY KEY (`id_proprietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`Imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`Imovel` (
  `id_imovel` INT NOT NULL,
  `logradouro_imovel` VARCHAR(75) NOT NULL,
  `numero_imovel` INT NULL,
  `bairro_imovel` VARCHAR(45) NOT NULL,
  `aluguel_imovel` DOUBLE NOT NULL,
  `id_proprietario` INT NOT NULL,
  PRIMARY KEY (`id_imovel`),
  INDEX `fk_Imovel_Proprietario_idx` (`id_proprietario` ASC),
  CONSTRAINT `fk_Imovel_Proprietario`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `imobiliaria`.`Proprietario` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`Cliente` (
  `id_inquilino` INT NOT NULL,
  `cpf_inquilino` VARCHAR(11) NOT NULL,
  `nome_inquilino` VARCHAR(100) NOT NULL,
  `email_cliente` VARCHAR(45) NOT NULL,
  `renda_inquilino` DOUBLE NOT NULL,
  `nascimento_inquilino` DATE NOT NULL,
  PRIMARY KEY (`id_inquilino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`Funcionario` (
  `id_funcionario` INT NOT NULL,
  `cpf_funcionario` VARCHAR(11) NOT NULL,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `nascimento_funcionario` DATE NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`Contrato` (
  `id_contrato` INT NOT NULL,
  `aluguel_contrato` DOUBLE NULL,
  `id_proprietario` INT NOT NULL,
  `id_inquilino` INT NOT NULL,
  `id_imovel` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_contrato`),
  INDEX `fk_Contrato_Proprietario1_idx` (`id_proprietario` ASC),
  INDEX `fk_Contrato_Cliente1_idx` (`id_inquilino` ASC),
  INDEX `fk_Contrato_Imovel1_idx` (`id_imovel` ASC),
  INDEX `fk_Contrato_Funcionario1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_Contrato_Proprietario1`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `imobiliaria`.`Proprietario` (`id_proprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Cliente1`
    FOREIGN KEY (`id_inquilino`)
    REFERENCES `imobiliaria`.`Cliente` (`id_inquilino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Imovel1`
    FOREIGN KEY (`id_imovel`)
    REFERENCES `imobiliaria`.`Imovel` (`id_imovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `imobiliaria`.`Funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
